

from src.config.default import _CN as cfg

cfg.TRAINER.MSLR_MILESTONES = [ 40, 80, 120, 160, 200]

cfg.TRAINER.TRUE_LR=2e-3
cfg.TRAINER.DATA_SAMPLER = 'scene_balance' 
cfg.TRAINER.N_SAMPLES_PER_SUBSET = 1024

cfg.MODEL.CODE_NUM=100
cfg.MODEL.D_MODEL=256
cfg.MODEL.RESNETFPN.BLOCK_DIMS = [128, 196, 256] 
cfg.MODEL.RESNETFPN.INITIAL_DIM = 128
cfg.MODEL.TRANS_BLOCK_NUM=6
cfg.MODEL.BACKBONE_FREEZE=True

cfg.DATASET.RANDOM_CROP=False
cfg.DATASET.RESOLUTION=480