



from src.config.default import _CN as cfg

cfg.TRAINER.MSLR_MILESTONES = [50, 100, 150, 200, 250, 300, 350]

cfg.TRAINER.TRUE_LR=2e-3
cfg.TRAINER.DATA_SAMPLER = 'scene_balance' 
cfg.TRAINER.N_SAMPLES_PER_SUBSET = 1024
cfg.TRAINER.SCORE_THRESH = 0.5
cfg.TRAINER.RANSAC_THRESH=48

cfg.MODEL.CODE_NUM=100
cfg.MODEL.D_MODEL=256
cfg.MODEL.RESNETFPN.BLOCK_DIMS = [128, 256, 256] 
cfg.MODEL.RESNETFPN.STRIDES = [2, 2, 1] 
cfg.MODEL.RESNETFPN.INITIAL_DIM = 64
cfg.MODEL.TRANS_BLOCK_NUM=6
cfg.MODEL.BACKBONE_FREEZE=False
cfg.MODEL.RGB=True

cfg.DATASET.RESOLUTION=720
cfg.DATASET.RANDOM_CROP=False

cfg.LOSS.SCALE=2.0
cfg.LOSS.SPARSITY_LOSS=True

