

from src.config.default import _CN as cfg

cfg.TRAINER.MSLR_MILESTONES = [30, 60, 90, 120, 150, 180, 210]

cfg.TRAINER.TRUE_LR=0.02
cfg.TRAINER.DATA_SAMPLER = 'scene_balance' 
cfg.TRAINER.N_SAMPLES_PER_SUBSET = 1024
cfg.TRAINER.SCORE_THRESH=0.5
cfg.TRAINER.CODE_LR_SCALE=1.0
cfg.TRAINER.CODE_FINETUNE=True

cfg.MODEL.CODE_NUM=50
cfg.MODEL.D_MODEL=256
cfg.MODEL.RESNETFPN.BLOCK_DIMS = [128, 256, 256] 
cfg.MODEL.RESNETFPN.STRIDES = [2, 2, 1] 
cfg.MODEL.RESNETFPN.INITIAL_DIM = 64
cfg.MODEL.TRANS_BLOCK_NUM=6
cfg.MODEL.BACKBONE_FREEZE=False
cfg.MODEL.RGB=True
cfg.MODEL.N_SAMPLE_POINTS = 2000
cfg.MODEL.N_SAMPLE_IN_VOXEL_POINTS = 1500

cfg.DATASET.MAX_N_POINTS=4800
cfg.DATASET.RANDOM_CROP=False
cfg.DATASET.RESOLUTION=480

cfg.LOSS.SPARSITY_LOSS=False

