

from src.config.default import _CN as cfg

cfg.TRAINER.MSLR_MILESTONES = [20, 40, 60, 80, 100, 120]

cfg.TRAINER.TRUE_LR=2e-3
cfg.TRAINER.DATA_SAMPLER = 'scene_balance' 
cfg.TRAINER.SCORE_THRESH=0.5
cfg.TRAINER.UNION_COORDS=True

cfg.MODEL.CODE_NUM=50
cfg.MODEL.D_MODEL=256
cfg.MODEL.RESNETFPN.BLOCK_DIMS = [128, 256, 256] 
cfg.MODEL.RESNETFPN.STRIDES = [2, 2, 1] 
cfg.MODEL.RESNETFPN.INITIAL_DIM = 64
cfg.MODEL.TRANS_BLOCK_NUM=6
cfg.MODEL.BACKBONE_FREEZE=False
cfg.MODEL.RGB=True
cfg.MODEL.N_SAMPLE_POINTS = 1000
cfg.MODEL.N_SAMPLE_IN_VOXEL_POINTS = 500

cfg.DATASET.RANDOM_CROP=False
cfg.DATASET.RESOLUTION=480
cfg.DATASET.ASPECT_RATIO=0.75

cfg.LOSS.SPARSITY_LOSS=False
